### ISSUE TITLE
gas estimation

### ISSUE THREAD

**Issue by alexander-camuto** [filecoin-saturn/contracts#11]
- forge estimation of fEVM gas costs is pretty finicky. Might be good to [import](https://hardhat.org/hardhat-runner/docs/advanced/hardhat-and-foundry) the hardhat [filecoin](https://github.com/filecoin-project/FEVM-Hardhat-Kit) into forge to get more reliable estimation. 

- compare and contrast how different IDE / packages estimate gas and post the results here as a markdown table.

**Comment by AmeanAsad** [comment]
@alexander-camuto closing, we already resolved our gas estimation issues with the development of our CLI.
