### ISSUE TITLE
Multi-sig interoperability with cli 

### ISSUE THREAD

**Issue by alexander-camuto** [filecoin-saturn/contracts#25]
Currently the wallet secret is loaded from a local file (good for testing bad for infosec). 
Ideally we'd want two things: 

- A safer way to connect a wallet to the cli without the use of a local mnemonic. 
- A way to propose new transactions using a multi-sig.

**Comment by yugborana** [comment]
hey, I would like to contribute if you could tell me about what needs to be done in the issues proposed by you? @alexander-camuto

**Comment by alexander-camuto** [comment]
> hey, I would like to contribute if you could tell me about what needs to be done in the issues proposed by you? @alexander-camuto

Hey @yugborana, thanks for reaching out. We've moved the utils to [here](https://github.com/filecoin-saturn/rs-fevm-utils/issues/1). What's the best way to coordinate to give you some tasks ?

**Comment by yugborana** [comment]
i am a beginner so would like to do first issue tasks with no background of programming languages as I am not well versed with it
